// 显式消解 WPF / WinForms / System.Drawing 之间的同名类型歧义
// WinForms 类型通过各文件顶部的 `using WinForms = System.Windows.Forms;` 别名访问
// System.Drawing 类型通过 `using Drawing = System.Drawing;` 别名访问
global using Application = System.Windows.Application;
global using Button = System.Windows.Controls.Button;
global using Panel = System.Windows.Controls.Panel;
global using TextBox = System.Windows.Controls.TextBox;
global using CheckBox = System.Windows.Controls.CheckBox;
global using Image = System.Windows.Controls.Image;
global using ListBox = System.Windows.Controls.ListBox;
global using Control = System.Windows.Controls.Control;
global using Border = System.Windows.Controls.Border;
global using Orientation = System.Windows.Controls.Orientation;
global using HorizontalAlignment = System.Windows.HorizontalAlignment;
global using Clipboard = System.Windows.Clipboard;
global using SystemColors = System.Windows.SystemColors;
global using Brushes = System.Windows.Media.Brushes;
global using FontFamily = System.Windows.Media.FontFamily;
global using Color = System.Windows.Media.Color;
global using Point = System.Windows.Point;
